pipeline:
  build:
    image: python:3.5.2
    environment:
        # I use dj_database_url to specify my DB settings
      - DATABASE_URL=postgres://postgres@localhost
    commands:
      - sleep 5 # (probably not necessary)
      - pip3 install -r requirements.txt
      - cd drone_tutorial
      - python ./manage.py test
      - cd ..
    when:
      branch: [ master ]
      event: [push, pull_request] # trigger step on push and pull events
  publish:
    image: plugins/docker
    email: pwensel@gmail.com
    tag: latest
    file: Dockerfile
    environment:
      - DOCKER_LAUNCH_DEBUG=true # usefull for debugging but not necessary )
    when:
      branch: [ master ]
      event: [ push ] # step only triggers on push events
services:
  database:
    image: postgres
    environment:
      - DATABASE_URL=postgres://postgres@localhost
